test: &default

  # Credentials for REST APIs
  client_id: <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_CLIENT_SECRET'] %>

  # Mode can be 'live' or 'sandbox'
  mode: <%= ENV['PAYPAL_ENV'] %>

  ssl_options:
    ca_file: null
  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
